### ISSUE TITLE
Can not compile Precise RoI Pooling library(after ./travis.sh)

### ISSUE THREAD

**Issue by Manguotree** [vacancy/PreciseRoIPooling#38]
Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
Traceback (most recent call last):
  File "/home/zqw/RT-MDNet-master/test.py", line 14, in <module>
    out = pool(features, rois)
  File "/home/zqw/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zqw/RT-MDNet-master/modules/preciseroipooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "/home/zqw/RT-MDNet-master/modules/preciseroipooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "/home/zqw/RT-MDNet-master/modules/preciseroipooling/pytorch/prroi_pool/functional.py", line 36, in _import_prroi_pooling
    raise ImportError('Can not compile Precise RoI Pooling library.')
ImportError: Can not compile Precise RoI Pooling library.
Loading extension module _prroi_pooling...

please help me,thanks!
after excute ./travis.sh ,it is ok but when i run test.py, above problem happend
my python=2.7  torch=0.4 and  cuda=8.0

**Comment by vacancy** [comment]
Can you show the internal error messages?

https://github.com/vacancy/PreciseRoIPooling/blob/master/pytorch/prroi_pool/functional.py#L35

There is an except token here. Can you help me to print the original Error message?
