### ISSUE TITLE
ImportError: undefined symbol: _Py_Dealloc

### ISSUE THREAD

**Issue by Csysmile** [vacancy/PreciseRoIPooling#39]
I have got the __prroi_pooling.so, but when I run the code, the error "ImportError: .../__prroi_pooling.so: undefined symbol: _Py_Dealloc"  occurred. The code stopped running in line “from .__prroi_pooling import lib as _lib, ffi as _ffi”. The pytorch I used is 0.4.0, cuda is 9.
Could you give me some advice about this?

Traceback (most recent call last):
  File "trainval_net.py", line 33, in <module>
    from model.faster_rcnn.vgg16 import vgg16
  File "/data/fasterrcnnpytorch1/lib/model/faster_rcnn/vgg16.py", line 16, in <module>
    from model.faster_rcnn.faster_rcnn import _fasterRCNN
  File "/data/fasterrcnnpytorch1/lib/model/faster_rcnn/faster_rcnn.py", line 15, in <module>
    from model.pre_align.modules.roi_prealign import PrRoIPool2D
  File "/data/fasterrcnnpytorch1/lib/model/pre_align/modules/roi_prealign.py", line 25, in <module>
    from ..functions.roi_prealign import prroi_pool2d
  File "/data/fasterrcnnpytorch1/lib/model/pre_align/functions/roi_prealign.py", line 14, in <module>
    from .._ext import _prroi_pooling
  File "/data/fasterrcnnpytorch1/lib/model/pre_align/_ext/_prroi_pooling/__init__.py", line 3, in <module>
    from .__prroi_pooling import lib as _lib, ffi as _ffi
ImportError: /data/fasterrcnnpytorch1/lib/model/pre_align/_ext/_prroi_pooling/__prroi_pooling.so: undefined symbol: _Py_Dealloc

**Comment by vacancy** [comment]
This looks like a mismatch between the python version you used when you compile the library and the python version you used for running the script.
