### ISSUE TITLE
RuntimeError: Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by sunhao12121** [vacancy/PreciseRoIPooling#48]
Thank u for your good jobs.  I get a strange problem with my code. Could u please help me.

I use the same code on two machine (one with 1080TI, one with2080TI). When the code is on the 1080TI(cuda 9.0 ,torch 1.1.0) ,everything goes well, I even have trained my model with the code. But when I use it on 2080 TI(cuda 10 ,pytorch 1.0.0), with same way, the code can't be compiled. 

I just run the simple code below , and it goes wrong

```
...
...
try:
            from os.path import join as pjoin, dirname
            from torch.utils.cpp_extension import load as load_extension
            root_dir = pjoin(dirname(__file__), 'src')

            _prroi_pooling = load_extension(
                '_prroi_pooling',
                [pjoin(root_dir, 'prroi_pooling_gpu.c'), pjoin(root_dir, 'prroi_pooling_gpu_impl.cu')],
                verbose=True
            )
        except ImportError:
            raise ImportError('Can not compile Precise RoI Pooling library.')
```
the message is below:

```
Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...

[1/3] /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/include -isystem /home/aaa/anaconda3/envs/ninja/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/aaa/ttt/ttt/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o

FAILED: prroi_pooling_gpu_impl.cuda.o 
/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/include -isystem /home/aaa/anaconda3/envs/ninja/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/aaa/ttt/ttt/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
/bin/sh: 1: /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/bin/nvcc: not found
[2/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/include -isystem /home/aaa/anaconda3/envs/ninja/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/aaa/ttt/ttt/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
FAILED: prroi_pooling_gpu.o 
c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/include -isystem /home/aaa/anaconda3/envs/ninja/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/aaa/ttt/ttt/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
In file included from /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/ATen/cuda/CUDAContext.h:5:0,
                 from /home/aaa/ttt/ttt/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:15:
/home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/ATen/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include "cuda_runtime_api.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/home/aaa/anaconda3/envs/ninja/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 31, in <module>
    _import_prroi_pooling()
  File "test.py", line 24, in _import_prroi_pooling
    verbose=True
  File "/home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension '_prroi_pooling'



```

its really wired. My friend can also use the 2080TI to train his model successfully. i think maybe some place (environment ?)is wrong. I do the same thing on 1080TI, Everything goes well. I guess maybe the problem is about the cuda. But 2080TI can only use cuda10.

I have read the other issue, they didn't work.

**Comment by vacancy** [comment]
The problem is:
```
In file included from /home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/ATen/cuda/CUDAContext.h:5:0,
                 from /home/aaa/ttt/ttt/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:15:
/home/aaa/anaconda3/envs/ninja/lib/python3.6/site-packages/torch/lib/include/ATen/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include "cuda_runtime_api.h"
          ^~~~~~~~~~~~~~~~~~~~
```

It looks like a problem with your cuda configuration issue. This line seems wrong to me:
```
-isystem /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/include
```
Maybe you have entered a wrong CUDA_HOME? Or CPATH?

**Comment by sunhao12121** [comment]
thank u for your help, it seems that my PATH is right, because i can run other code with cuda. anyway thanks a lot, I dececide  to use another machine. thanks
