### ISSUE TITLE
compiling error when executing ./travis.sh

### ISSUE THREAD

**Issue by bwcxa** [vacancy/PreciseRoIPooling#50]
**My pytorch version is 0.4.0 and I meet the compiling error as follows:**
Working directory:  /home/ziwen/All/PreciseRoIPooling/pytorch/prroi_pool/src
Compiling prroi_pooling kernels by nvcc...
Working directory:  /home/ziwen/All/PreciseRoIPooling/pytorch/prroi_pool
Building python libraries...
generating /tmp/tmpqoxl3f7f/__prroi_pooling.c
running build_ext
building '__prroi_pooling' extension
creating home
creating home/ziwen
creating home/ziwen/All
creating home/ziwen/All/PreciseRoIPooling
creating home/ziwen/All/PreciseRoIPooling/pytorch
creating home/ziwen/All/PreciseRoIPooling/pytorch/prroi_pool
creating home/ziwen/All/PreciseRoIPooling/pytorch/prroi_pool/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/ziwen/anaconda3/envs/gan/include/python3.6m -c __prroi_pooling.c -o ./__prroi_pooling.o
In file included from /home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THVector.h:5:0,
                 from /home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:12,
                 from __prroi_pooling.c:433:
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_polevl’:
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:134:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i <= len; i++) {
   ^
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:134:3: note: use option -std=c99 or -std=gnu99 to compile your code
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_polevlf’:
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:142:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i <= len; i++) {
   ^
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigamma’:
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:260:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 6; ++i) {
   ^
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigammaf’:
/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:278:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 6; ++i) {
   ^
Traceback (most recent call last):
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 49, in <module>
    ffi.build()
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/ziwen/anaconda3/envs/gan/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
So how can I fix this bug? Thanks much.

**Comment by vacancy** [comment]
try `export CC=g++` before running the code?
