### ISSUE TITLE
RuntimeError: Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by n1-k0** [vacancy/PreciseRoIPooling#59]
hello! I meet this error and don't know how to solve it, can you give me some help?
environment is 2080ti   torchvision==0.3.0     pytorch1.1.0     cuda10.0
---
`
 Using /tmp/torch_extensions as PyTorch extensions root...

Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
[1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
FAILED: prroi_pooling_gpu_impl.cuda.o
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu(1): error: expected a declaration

1 error detected in the compilation of "/tmp/tmpxft_00006619_00000000-6_prroi_pooling_gpu_impl.cpp1.ii".
[2/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
FAILED: prroi_pooling_gpu.o
c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
In file included from /root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:19:
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh:1:1: error: expected unqualified-id before ‘.’ token
 ../../../src/prroi_pooling_gpu_impl.cuh
 ^
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘at::Tensor prroi_pooling_backward_cuda(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float)’:
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:66:5: error: ‘PrRoIPoolingBackwardGpu’ was not declared in this scope
     PrRoIPoolingBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:66:5: note: suggested alternative: ‘prroi_pooling_backward_cuda’
     PrRoIPoolingBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~
     prroi_pooling_backward_cuda
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘at::Tensor prroi_pooling_coor_backward_cuda(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float)’:
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:97:5: error: ‘PrRoIPoolingCoorBackwardGpu’ was not declared in this scope
     PrRoIPoolingCoorBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:97:5: note: suggested alternative: ‘prroi_pooling_coor_backward_cuda’
     PrRoIPoolingCoorBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
     prroi_pooling_coor_backward_cuda
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘void pybind11_init__prroi_pooling(pybind11::module&)’:
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:110:42: error: ‘prroi_pooling_forward_cuda’ was not declared in this scope
     m.def("prroi_pooling_forward_cuda", &prroi_pooling_forward_cuda, "PRRoIPooling_forward");
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:110:42: note: suggested alternative: ‘prroi_pooling_backward_cuda’
     m.def("prroi_pooling_forward_cuda", &prroi_pooling_forward_cuda, "PRRoIPooling_forward");
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                          prroi_pooling_backward_cuda
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 949, in _build_extension_module
    check=True)
  File "/root/anaconda3/envs/TracKit/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tracking/run_video.py", line 230, in <module>
    main()
  File "tracking/run_video.py", line 227, in main
    track_video(siam_tracker, online_tracker, siam_net, args.video, init_box=args.init_bbox, args=args)
  File "tracking/run_video.py", line 101, in track_video
    online_tracker.init(frame_disp, rgb_im, siam_net, target_pos, target_sz, True, dataname='VOT2019', resume=args.resume)
  File "/root/niko/TracKit/tracking/../lib/tracker/online.py", line 123, in init
    self.init_classifier(init_backbone_feat)
  File "/root/niko/TracKit/tracking/../lib/tracker/online.py", line 579, in init_classifier
    compute_losses=plot_loss)
  File "/root/niko/TracKit/tracking/../lib/models/online/classifier/linear_filter.py", line 99, in get_filter
    weights = self.filter_initializer(feat, bb)
  File "/root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/niko/TracKit/tracking/../lib/models/online/classifier/initializer.py", line 165, in forward
    weights = self.filter_pool(feat, bb)
  File "/root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/niko/TracKit/tracking/../lib/models/online/classifier/initializer.py", line 49, in forward
    return self.prroi_pool(feat, roi1)
  File "/root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/niko/TracKit/tracking/../lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "/root/niko/TracKit/tracking/../lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "/root/niko/TracKit/tracking/../lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "/root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "/root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 866, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/root/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 962, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension '_prroi_pooling'
`

**Comment by vacancy** [comment]
Please git clone the repo. It contains symbol links

**Comment by n1-k0** [comment]
> Please git clone the repo. It contains symbol links

Thank you. I had try it. but still have this error

**Comment by vacancy** [comment]
please check if /root/niko/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh

is a valid symbol link.

**Comment by n1-k0** [comment]
thank you for your patience. 
my problem just like [this](https://github.com/vacancy/PreciseRoIPooling/issues/58),I git clone in windows and upload to the ubuntu resulting in this problem.

**Comment by vacancy** [comment]
Thanks for reporting. Putting up an updated note in the readme about windows git versions.

**Comment by n1-k0** [comment]
> Thanks for reporting. Putting up an updated note in the readme about windows git versions.

I do not really understand your meaning. Should I remind not to do like me in the readme?

**Comment by vacancy** [comment]
No worries. I have put some notes in the README of this repo.

**Comment by zuzi2015** [comment]
Have you solved this problem? I met same question. @n1-k0
