### ISSUE TITLE
RuntimeError: Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by yuyudiandian** [vacancy/PreciseRoIPooling#65]
Using /home/yy/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/yy/.cache/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /home/yy/tools/cuda-9.0:/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output prroi_pooling_gpu_impl.cuda.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/TH -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/THC -isystem /home/yy/tools/cuda-9.0:/usr/local/cuda/include -isystem /home/yry/data/anaconda3/envs/transyry/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/yy/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o 
FAILED: prroi_pooling_gpu_impl.cuda.o 
/home/yy/tools/cuda-9.0:/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output prroi_pooling_gpu_impl.cuda.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/TH -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/THC -isystem /home/yy/tools/cuda-9.0:/usr/local/cuda/include -isystem /home/yry/data/anaconda3/envs/transyry/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/yy/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o 
/bin/sh: 1: /home/yy/tools/cuda-9.0:/usr/local/cuda/bin/nvcc: not found
[2/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/TH -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/THC -isystem /home/yy/tools/cuda-9.0:/usr/local/cuda/include -isystem /home/yry/data/anaconda3/envs/transyry/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/yy/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o 
FAILED: prroi_pooling_gpu.o 
c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/TH -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/THC -isystem /home/yy/tools/cuda-9.0:/usr/local/cuda/include -isystem /home/yry/data/anaconda3/envs/transyry/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/yy/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o 
In file included from /home/yy/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:15:0:
/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yy/data/TransformerTrack/pytracking/GOT10k_GOT.py", line 46, in <module>
    experiment.run(tracker, visualize=False)
  File "/home/yy/.local/lib/python3.7/site-packages/got10k/experiments/got10k.py", line 81, in run
    img_files, anno[0, :], visualize=visualize)
  File "/home/yy/.local/lib/python3.7/site-packages/got10k/trackers/__init__.py", line 35, in track
    self.init(image, box)
  File "/home/yy/data/TransformerTrack/pytracking/GOT10k_GOT.py", line 32, in init
    self.tracker.initialize(image, box)
  File "/home/yy/data/TransformerTrack/pytracking/tracker/trdimp/trdimp_for_GOT.py", line 90, in initialize
    self.init_classifier(init_backbone_feat)
  File "/home/yy/data/TransformerTrack/pytracking/tracker/trdimp/trdimp_for_GOT.py", line 620, in init_classifier
    compute_losses=plot_loss)
  File "/home/yy/data/TransformerTrack/ltr/models/target_classifier/linear_filter.py", line 114, in get_filter
    weights = self.filter_initializer(feat, bb)
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yy/data/TransformerTrack/ltr/models/target_classifier/initializer.py", line 164, in forward
    weights = self.filter_pool(feat, bb)
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yy/data/TransformerTrack/ltr/models/target_classifier/initializer.py", line 45, in forward
    return self.prroi_pool(feat, roi1)
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yy/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "/home/yy/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "/home/yy/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1407, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_prroi_pooling'
![image](https://user-images.githubusercontent.com/71555221/125075330-09bc2f00-e0f1-11eb-9c8d-7996763a9559.png)
[1/3] /home/yy/tools/cuda-9.0:/usr/local/cuda/bin/nvcc Thank you for this excellent work! But I met some trouble.My environment is 3090 cuda11.2 and pytorch1.7.1, but i don't why"[1/3] /home/yy/tools/cuda-9.0:" will come out, and i modified the ~/.bashrc ,but it seems doesn't work, can you give me some advice? Thank you very much.

**Comment by yuyudiandian** [comment]
![image](https://user-images.githubusercontent.com/71555221/125076096-11c89e80-e0f2-11eb-9661-6ce6d426ad0e.png)
and this is my environment , and I have already source ~/.bashrc.But why it still has "[1/3] /home/yy/tools/cuda-9.0:/usr/local/cuda/bin/nvcc"？

**Comment by vacancy** [comment]
There is a typo in your bashrc: remove the $ before /usr/local in CUDA_HOME
But I don't what triggered the wrong path for nvcc. Have you sourced your bashrc after modifying it? Can you type `export` in your bash and paste the results?

**Comment by yuyudiandian** [comment]
This my export results
declare -x CLUTTER_IM_MODULE="xim"
declare -x COLORTERM="truecolor"
declare -x CONDA_DEFAULT_ENV="base"
declare -x CONDA_EXE="/home/yry/data/anaconda3/bin/conda"
declare -x CONDA_PREFIX="/home/yry/data/anaconda3"
declare -x CONDA_PROMPT_MODIFIER="(base) "
declare -x CONDA_PYTHON_EXE="/home/yry/data/anaconda3/bin/python"
declare -x CONDA_SHLVL="1"
declare -x CUDA_HOME=":/usr/local/cuda"
declare -x DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/999/bus,guid=7a26be39e2b1ff8220c0481960e80dcd"
declare -x DBUS_STARTER_ADDRESS="unix:path=/run/user/999/bus,guid=7a26be39e2b1ff8220c0481960e80dcd"
declare -x DBUS_STARTER_BUS_TYPE="session"
declare -x DISPLAY=":12.0"
declare -x GNOME_DESKTOP_SESSION_ID="this-is-deprecated"
declare -x GNOME_SHELL_SESSION_MODE="ubuntu"
declare -x GNOME_TERMINAL_SCREEN="/org/gnome/Terminal/screen/dc2ad4a4_a28a_4427_b464_eeaa8f7bac22"
declare -x GNOME_TERMINAL_SERVICE=":1.75"
declare -x GPG_AGENT_INFO="/run/user/999/gnupg/S.gpg-agent:0:1"
declare -x GTK_IM_MODULE="ibus"
declare -x GTK_MODULES="gail:atk-bridge"
declare -x HOME="/home/yy"
declare -x IM_CONFIG_PHASE="1"
declare -x INVOCATION_ID="f492ade558c941d29e43364cdb2ee048"
declare -x JOURNAL_STREAM="9:49092"
declare -x LANG="en_US.UTF-8"
declare -x LC_ADDRESS="zh_CN.UTF-8"
declare -x LC_IDENTIFICATION="zh_CN.UTF-8"
declare -x LC_MEASUREMENT="zh_CN.UTF-8"
declare -x LC_MONETARY="zh_CN.UTF-8"
declare -x LC_NAME="zh_CN.UTF-8"
declare -x LC_NUMERIC="zh_CN.UTF-8"
declare -x LC_PAPER="zh_CN.UTF-8"
declare -x LC_TELEPHONE="zh_CN.UTF-8"
declare -x LC_TIME="zh_CN.UTF-8"
declare -x LD_LIBRARY_PATH=":/usr/local/cuda/lib64"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="yy"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x MANAGERPID="4143"
declare -x OLDPWD
declare -x PATH="/home/yy/anaconda3/bin:/home/yry/data/anaconda3/bin:/home/yry/data/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin"
declare -x PULSE_SCRIPT="/etc/xrdp/pulse/default.pa"
declare -x PWD="/usr/local"
declare -x QT4_IM_MODULE="xim"
declare -x QT_ACCESSIBILITY="1"
declare -x QT_IM_MODULE="ibus"
declare -x SESSION_MANAGER="local/node-W560-G20:@/tmp/.ICE-unix/4155,unix/node-W560-G20:/tmp/.ICE-unix/4155"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_AGENT_PID="4254"
declare -x SSH_AUTH_SOCK="/run/user/999/keyring/ssh"
declare -x TERM="xterm-256color"
declare -x UID="999"
declare -x USER="yy"
declare -x VTE_VERSION="5202"
declare -x XDG_CONFIG_DIRS="/etc/xdg/xdg-ubuntu:/etc/xdg"
declare -x XDG_CURRENT_DESKTOP="ubuntu:GNOME"
declare -x XDG_DATA_DIRS="/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop"
declare -x XDG_MENU_PREFIX="gnome-"
declare -x XDG_RUNTIME_DIR="/run/user/999"
declare -x XDG_SESSION_ID="c5"
declare -x XMODIFIERS="@im=ibus"
declare -x XRDP_SESSION="1"
declare -x XRDP_SOCKET_PATH="/var/run/xrdp/sockdir"
declare -x _CE_CONDA=""
declare -x _CE_M=""

**Comment by yuyudiandian** [comment]
[1/3] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output prroi_pooling_gpu_impl.cuda.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/TH -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/THC -isystem /home/yry/data/anaconda3/envs/transyry/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/yry/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o 
FAILED: prroi_pooling_gpu_impl.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output prroi_pooling_gpu_impl.cuda.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/TH -isystem /home/yry/data/anaconda3/envs/transyry/lib/python3.7/site-packages/torch/include/THC -isystem /home/yry/data/anaconda3/envs/transyry/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/yry/data/TransformerTrack/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o 
cc1plus: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
上面的问题我换了一个账号解决了 但是[1/3] /usr/bin/nvcc我看了并不存在这个东西 并且我在另一台成功的机子上面，这段内容是[1/3] /usr/local/cuda-10.1/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/wyf/data/anaconda3/envs/py16/lib/python3.7/site-packages/torch/include -isystem /home/wyf/data/anaconda3/envs/py16/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/wyf/data/anaconda3/envs/py16/lib/python3.7/site-packages/torch/include/TH -isystem /home/wyf/data/anaconda3/envs/py16/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.1/include -isystem /home/wyf/data/anaconda3/envs/py16/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/yy/data/TransformerTrack-new/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
我想知道如何修改[1/3] /usr/bin/nvcc到[1/3] /usr/local/cuda-10.1/bin/nvcc，第二个才是正确路径，尝试修改环境变量但是好像source也没有用

**Comment by yuyudiandian** [comment]
终于知道解决的方法了 通过vim /etc/enviroment, 在其中添加:/usr/local/cuda-11.2/bin/nvcc 并重启系统解决 ，其中cuda-11.2根据自己cuda自行修改！
