### ISSUE TITLE
ImportError: Can not compile Precise RoI Pooling library.

### ISSUE THREAD

**Issue by SinHanYang** [vacancy/PreciseRoIPooling#77]
Hi, I tried to execute another GitHub repo [dissect](https://github.com/davidbau/dissect) which uses your product. However, it shows error:
```
Traceback (most recent call last):
  File "./dissect_continual-master/netdissect/upsegmodel/prroi_pool/functional.py", line 22, in <module>
    verbose=False
  File "./denv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1214, in load
    keep_intermediates=keep_intermediates)
  File "./denv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1450, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "./denv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1844, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: ~/.cache/torch_extensions/py37_cu102/_prroi_pooling/_prroi_pooling.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./denv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "./denv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./dissect_continual-master/experiment/dissect_experiment.py", line 335, in <module>
    main()
  File "./dissect_continual-master/experiment/dissect_experiment.py", line 119, in main
    segmodel, seglabels, segcatlabels = setting.load_segmenter(args.seg)
  File "./dissect_continual-master/experiment/setting.py", line 86, in load_segmenter
    segdiv=('quad' if quad_seg else None)))
  File "./dissect_continual-master/netdissect/segmenter.py", line 143, in __init__
    segarch, segvocab, epoch)
  File "./dissect_continual-master/netdissect/segmenter.py", line 583, in load_unified_parsing_segmentation_model
    weights=os.path.join(segmodel_dir, 'decoder_epoch_%d.pth' % epoch))
  File "./dissect_continual-master/netdissect/upsegmodel/models.py", line 201, in build_decoder
    fpn_dim=512)
  File "./dissect_continual-master/netdissect/upsegmodel/models.py", line 257, in __init__
    from .prroi_pool import PrRoIPool2D
  File "./dissect_continual-master/netdissect/upsegmodel/prroi_pool/__init__.py", line 12, in <module>
    from .prroi_pool import *
  File "./dissect_continual-master/netdissect/upsegmodel/prroi_pool/prroi_pool.py", line 14, in <module>
    from .functional import prroi_pool2d
  File "./dissect_continual-master/netdissect/upsegmodel/prroi_pool/functional.py", line 25, in <module>
    raise ImportError('Can not compile Precise RoI Pooling library.')
ImportError: Can not compile Precise RoI Pooling library.
```

The environment is:
```
python 3.7
cudatoolkit 10.2
pytorch 1.12.0
ninja 1.10.2.3
```

What should I do to pass this error? Thanks

**Comment by EavanLi** [comment]
Did you solve this problem please? Looking forward to answer

**Comment by SinHanYang** [comment]
> 

Yes, I use `pytorch 1.10.0` instead. Also, `Ninja` is necessary.
