### ISSUE TITLE
Unable to compile for windows + torch 2.0.1

### ISSUE THREAD

**Issue by FawadAbbas12** [vacancy/PreciseRoIPooling#81]
I am trying to use PreciseRoIPooling with pytorch 2.0, cuda 11.7 and it successfully compiles for ubuntu with same configurations as listed for windows but on windows i am unable to either load it using jit or compile it to pyd/dll

## Known Issues 
- I have assured that symlink issue is resolved

# Env Setup
### Torch
torch==2.0.1+cu117  
### VS build tool 
Tested on 2017&19
### NVCC venison
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

# Compilation Results [(complete logs here)](https://gist.github.com/FawadAbbas12/9618a4d9d267a49cc91bd5ad996e25f6)
```
Using c:AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file c:AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\_prroi_pooling\build.ninja...
Building extension module _prroi_pooling...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] cl /showIncludes -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\torch\csrc\api\include -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\TH -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -Ic:anaconda3\envs\torch-gpu\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -c c:Desktop\app\share\PreciseRoIPooling\pytorch\prroi_pool\src\prroi_pooling_gpu.c /Foprroi_pooling_gpu.o 
FAILED: prroi_pooling_gpu.o 
cl /showIncludes -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\torch\csrc\api\include -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\TH -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -Ic:anaconda3\envs\torch-gpu\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -c c:Desktop\app\share\PreciseRoIPooling\pytorch\prroi_pool\src\prroi_pooling_gpu.c /Foprroi_pooling_gpu.o 
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27051 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\torch/csrc/utils/python_stub.h(4): error C2061: syntax error: identifier 'PyObject'
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\torch/csrc/utils/python_stub.h(4): error C2059: syntax error: ';'
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\torch/csrc/utils/python_stub.h(4): error C2513: ' ': no variable declared before '='
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\torch/csrc/utils/python_stub.h(4): error C2065: '_object': undeclared identifier
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\c10/macros/Macros.h(138): warning C4067: unexpected tokens following preprocessor directive - expected a newline
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\c10/macros/Macros.h(148): error C2061: syntax error: identifier 'c10'
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\c10/macros/Macros.h(148): error C2059: syntax error: ';'
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\c10/macros/Macros.h(148): error C2449: found '{' at file scope (missing function header?)
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\c10/macros/Macros.h(148): error C2059: syntax error: '}'
.
.
.
.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xtr1common(337): error C2059: syntax error: '}'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\type_traits(571): error C4233: nonstandard extension used: '__is_union' keyword only supported in C++, not C
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\type_traits(581): error C4233: nonstandard extension used: '__is_class' keyword only supported in C++, not C
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\type_traits(616): error C4233: nonstandard extension used: '__is_convertible_to' keyword only supported in C++, not C
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\type_traits(627): error C4233: nonstandard extension used: '__is_enum' keyword only supported in C++, not C
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\type_traits(704): error C4233: nonstandard extension used: '__is_pod' keyword only supported in C++, not C
.
.
.
.
.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\istream(745): warning C4157: pragma was ignored by C compiler
c:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\c10/util/C++17.h(27): fatal error C1189: #error:  You need C++14 to compile PyTorch
[2/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc --generate-dependencies-with-compile --dependency-output prroi_pooling_gpu_impl.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\torch\csrc\api\include -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\TH -Ic:anaconda3\envs\torch-gpu\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -Ic:anaconda3\envs\torch-gpu\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -c c:Desktop\app\share\PreciseRoIPooling\pytorch\prroi_pool\src\prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
prroi_pooling_gpu_impl.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "c:anaconda3\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "c:anaconda3\envs\torch-gpu\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    _import_prroi_pooling()
  File "c:Desktop\app\share\PreciseRoIPooling\pytorch\prroi_pool\functional.py", line 30, in _import_prroi_pooling
    _prroi_pooling = load_extension(
  File "c:anaconda3\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "c:anaconda3\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "c:anaconda3\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "c:anaconda3\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_prroi_pooling'

```

**Comment by FawadAbbas12** [comment]
Solved it by using docker container

**Comment by STAR-811** [comment]
@FawadAbbas12 could you tell me how you ensure that 'I have assured that symlink issue is resolved'? I encounter the same question as you. T_T

**Comment by FawadAbbas12** [comment]
> @FawadAbbas12 could you tell me how you ensure that 'I have assured that symlink issue is resolved'? I encounter the same question as you. T_T

I just replaced symlink with original files.
![Screenshot_20240505-182248_GitHub.jpg](https://github.com/vacancy/PreciseRoIPooling/assets/36898352/dde7f993-e90f-410e-8527-467dae511e9f)
